export enum StateKey {
  HIDE_SIP_WARNING = 'HIDE_SIP_WARNING',
  PREVIEWED_DEMO = 'PREVIEWED_DEMO',
  FORM_IS_UNSAVED = 'FORM_IS_UNSAVED',
  SHOW_UNSAVED_MODAL = 'SHOW_UNSAVED_MODAL'
}

export enum WEATHER_RESPONSE_UNITS {
  IMPERIAL = 'imperial',
  METRIC = 'metric',
  STANDARD = 'standard'
}
