export enum StateKey {
  HIDE_SIP_WARNING = 'HIDE_SIP_WARNING',
  PREVIEWED_DEMO = 'PREVIEWED_DEMO',
  FORM_IS_UNSAVED = 'FORM_IS_UNSAVED',
  SHOW_UNSAVED_MODAL = 'SHOW_UNSAVED_MODAL',
  SELECTED_DEMO_CARD = 'SELECTED_DEMO_CARD',
  USER_ID = 'USER_ID',
  SHOW_ERROR_MODAL = 'SHOW_ERROR_MODAL',
  FORM = 'FORM',
  TARGET_DEMO_ID = 'TARGET_DEMO_ID',
  DEMO_IS_LOADING = 'DEMO_IS_LOADING'
}

export enum WEATHER_RESPONSE_UNITS {
  IMPERIAL = 'imperial',
  METRIC = 'metric',
  STANDARD = 'standard'
}
